### ISSUE TITLE
typeError: float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by peaceng** [revorg7/viola-jones#1]
excuse me
im looking for viola jones face detection in variant scale for my school work, and i found this repository maybe can help me with that. but when i run  final.py i got typeerror : float' object cannot be interpreted as an integer, 

at line 20 h_list = range(k,n+k,k), in calc har().

i look for some solution at stackoverflow, but i still get that error.

is there anything i  #missed,? 
sorry if i dont speak english well :(

**Comment by revorg7** [comment]
Hi,
one of the arguments to range(k,n+k,k) is not integer (either k or n). check using python debug library, called pdb:
import pdb
at line 19 pdb.set_trace()
at line 20 h_list = range(k,n+k,k)

then check the values of k and n.

**Comment by peaceng** [comment]
i'v change  n value from decimal as integer. then i got an error at evaluate haar feature> 

indexerror: index 3 is out of bounds for axis 1 with size

im looking at http://stackoverflow.com/questions/19297790/fastest-python-way-to-evaluate-haar-feature-values

but i dont  find any clue

**Comment by revorg7** [comment]
There is no fast way to calculate harr-features in Python, because Python
is a slow language. I faced this issue myself, so I pre-calculated
harr-features on my training data which took me 20 mins (this I already
mentioned in my readme.md).
Finally, I must warn you that my final system didn't work at all, since I
didn't implement cascading. I just implemented the single monolithic
classifier and it didn't give good performance.
